# Use `brew bundle` to install

brew 'awscli'
brew 'bash'
brew 'coreutils'
brew 'ctags'
brew 'curl'
brew 'fortune'
brew 'fzf'                 # fuzzy file finder
brew 'gawk'
brew 'gh'
brew 'git'
brew 'gnu-tar'
brew 'gnupg2'
brew 'go'
brew 'grip'                # GitHub style Markdown live previews
brew 'htop'
brew 'hub'
brew 'jq'
brew 'lolcat'
brew 'lua'
brew 'mas'
brew 'mtr'
brew 'neofetch'            # system info
brew 'neovim'
brew 'netcat'
brew 'nmap'
brew 'nvm'
brew 'nyancat'
brew 'pinentry-mac'
brew 'starship'             # cross-shell prompt
brew 'stow'
brew 'tflint'
brew 'the_silver_searcher'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'watch'
brew 'wget'
brew 'ykman'
brew 'zsh'
brew 'zsh-history-substring-search'

cask '1password'
cask 'firefox'
cask 'font-hack-nerd-font' # Hack font glyphs
cask 'iterm2'
cask 'raycast'
cask 'reader'              # Readwise Reader
cask 'rectangle'
cask 'spotify'

mas 'Bear', id: 1091189122
mas 'Cardhop', id: 1290358394
mas 'Fantastical', id: 975937182
mas 'Slack', id: 803453959
mas 'Todoist', id: 585829637
