############################################
# Brewfile
# https://robots.thoughtbot.com/brewfile-a-gemfile-but-for-homebrew
############################################
# To use, simply run
# > brew tap homebrew/bundle && brew bundle
############################################

tap "homebrew/bundle"
tap "homebrew/core"

brew 'awscli'
brew 'bash'
brew 'coreutils'
brew 'ctags'
brew 'curl'
brew 'dnsmasq'
brew 'fortune'
brew 'fzf'                 # fuzzy file finder
brew 'git'
brew 'gnupg2'
brew 'gnu-tar'
brew 'grip'                # GitHub style Markdown live previews
brew 'htop-osx'
brew 'hub'
brew 'jq'
brew 'lua'
brew 'neofetch'            # system info
brew 'neovim'
brew 'netcat'
brew 'nmap'
brew 'nyancat'
brew 'openssl'
brew 'pinentry-mac'
brew 'spark'               # sparklines
brew 'the_silver_searcher'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'watch'
brew 'wget'
brew 'zsh'

tap "homebrew/cask-fonts"
cask "font-hack-nerd-font" # Hack font glyphs
