#!/bin/bash

main() {
  if ! pgrep -x spotify >/dev/null; then
    echo ""; exit
  fi
  if [[ "$(playerctl status)" == "Paused" ]]; then
    echo ""; exit
  fi
  artist=$(playerctl metadata artist)
  title=$(playerctl metadata title)
  status=$(playerctl status)
  echo $title - $artist

}

main "$@"

