#!/usr/bin/env bash

SPOTIFY_TRACK=$(osascript <<EOF
if application "Spotify" is running then
  tell application "Spotify"
    set currArtist to artist of current track as string
    set currTrack to name of current track as string
    return currArtist & " - " & currTrack
  end tell
end if
EOF)

test -n "$SPOTIFY_TRACK" && echo '♫ ' $SPOTIFY_TRACK ' |'
